version: '3'
services:
  redis:
    image: redisdb:v1
    ports:
      - "6379:6379"
  process1:
    image: data-pusher-process1:v1
    ports:
       - "8081:8080"
  process2:
    image: data-pusher-process2:v1
    ports:
       - "8082:8080"
  process3:
    image: data-pusher-process3:v1
    ports:
       - "8083:8080"
  process4:
    image: data-pusher-process4:v1
    ports:
       - "8084:8080"
